### ISSUE TITLE
Side scrolling

### ISSUE THREAD

**Issue by codethecoffee** [codethecoffee/game#2]
Make the level scroll to the right with the player to reveal the rest of the level.

**Comment by codethecoffee** [comment]
As suggested by @mtruong68 we'll just make the camera follow the player sprite instead of implementing a separate side scrolling functionality

**Comment by mtruong68** [comment]
ended up actually writing a script for it bc i got tired of trying to figure out how to stop the camera rotation when the player rotated :-/// right now you have to manually input the viewport bounds of the the level to prevent the camera exceeding the games viewport, but maybe that can be handled automatically
